#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/windows/servercore:1809 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["AIMS.APIs/AIMS.APIs.csproj", "AIMS.APIs/"]
COPY ["AIMS.Models/AIMS.Models.csproj", "AIMS.Models/"]
COPY ["AIMS.DAL/AIMS.DAL.csproj", "AIMS.DAL/"]
COPY ["AIMS.Services/AIMS.Services.csproj", "AIMS.Services/"]
RUN dotnet restore "AIMS.APIs/AIMS.APIs.csproj"
COPY . .
WORKDIR "/src/AIMS.APIs"
RUN dotnet build "AIMS.APIs.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "AIMS.APIs.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "AIMS.APIs.dll"]